# Generated by Django 3.2.6 on 2021-12-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_email_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lang',
            field=models.CharField(default='en', max_length=200, null=True, verbose_name='Language'),
        ),
    ]
