# Generated by Django 4.0 on 2021-12-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='default.jpg', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='default.jpg', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(default='default.jpg', upload_to='uploads/'),
        ),
    ]
