# Generated by Django 4.0 on 2022-01-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
