# Generated by Django 4.0 on 2022-01-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='productServices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productservices'),
        ),
    ]
