# Generated by Django 4.0 on 2022-01-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_orderitem_productservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservices',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
