# Generated by Django 4.0 on 2022-01-11 07:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_productservices_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=tinymce.models.HTMLField(default='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=tinymce.models.HTMLField(default='description'),
        ),
        migrations.AlterField(
            model_name='productservices',
            name='description',
            field=tinymce.models.HTMLField(default='description'),
        ),
        migrations.AlterField(
            model_name='productservices',
            name='description_ru',
            field=tinymce.models.HTMLField(default='description'),
        ),
        migrations.AlterField(
            model_name='productservices',
            name='description_uz',
            field=tinymce.models.HTMLField(default='description'),
        ),
    ]
