# Generated by Django 4.0 on 2022-01-11 07:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='line',
            field=tinymce.models.HTMLField(default='line'),
        ),
        migrations.AddField(
            model_name='product',
            name='line_ru',
            field=tinymce.models.HTMLField(default='line'),
        ),
        migrations.AddField(
            model_name='product',
            name='line_uz',
            field=tinymce.models.HTMLField(default='line'),
        ),
        migrations.AddField(
            model_name='productservices',
            name='line',
            field=tinymce.models.HTMLField(default='line'),
        ),
        migrations.AddField(
            model_name='productservices',
            name='line_ru',
            field=tinymce.models.HTMLField(default='line'),
        ),
        migrations.AddField(
            model_name='productservices',
            name='line_uz',
            field=tinymce.models.HTMLField(default='line'),
        ),
    ]
