# Generated by Django 4.0 on 2022-01-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_line_product_line_ru_product_line_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='productservices',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='productservices',
            name='description_ru',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='productservices',
            name='description_uz',
            field=models.TextField(default='description'),
        ),
    ]
