# Generated by Django 4.0 on 2021-12-29 11:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_subtitle', models.CharField(max_length=200)),
                ('news_date', models.DateTimeField(auto_now_add=True)),
                ('news_text', tinymce.models.HTMLField()),
            ],
        ),
    ]
