# Generated by Django 4.0 on 2021-12-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_subtitle',
            field=models.TextField(),
        ),
    ]
