# Generated by Django 4.0 on 2022-01-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextsToTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField()),
                ('text_en', models.TextField()),
            ],
        ),
    ]
