# Generated by Django 4.0 on 2022-01-08 08:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_textstotranslate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textstotranslate',
            name='text_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='textstotranslate',
            name='text_ru',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='textstotranslate',
            name='text_uz',
            field=tinymce.models.HTMLField(),
        ),
    ]
