# Generated by Django 4.0 on 2022-01-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dealers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True)),
                ('user_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=40, null=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
