# Generated by Django 4.0 on 2022-01-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='city',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
