# Generated by Django 4.0 on 2022-01-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_title_feedback_city_feedback_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
