# Generated by Django 4.0 on 2022-01-14 10:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='working_days',
            field=tinymce.models.HTMLField(default='24/7'),
        ),
    ]
