# Generated by Django 4.0 on 2022-01-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_dealers_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealers',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dealers',
            name='region',
            field=models.CharField(default='', max_length=200),
        ),
    ]
